models/Faqs.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "faqs".
 *
 * @property int $id
 * @property int $category_id
 * @property string $question_ru
 * @property string $question_uz
 * @property string $question_en
 * @property string $answer_ru
 * @property string $answer_uz
 * @property string $answer_en
 * @property int $status
 * @property int $order
 * @property int $created_at
 * @property int $updated_at
 *
 * @property FaqCategories $category
 */
class Faqs extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'faqs';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id'], 'required'],
            [['category_id', 'status', 'order', 'created_at', 'updated_at'], 'integer'],
            [['question_ru', 'question_uz', 'question_en'], 'string', 'max' => 255],
            [['answer_ru', 'answer_uz', 'answer_en'],'string'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => FaqCategories::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'category_id' => Yii::t('app', 'Category ID'),
            'question_ru' => Yii::t('app', 'Question Ru'),
            'question_uz' => Yii::t('app', 'Question Uz'),
            'question_en' => Yii::t('app', 'Question En'),
            'answer_ru' => Yii::t('app', 'Answer Ru'),
            'answer_uz' => Yii::t('app', 'Answer Uz'),
            'answer_en' => Yii::t('app', 'Answer En'),
            'status' => Yii::t('app', 'Status'),
            'order' => Yii::t('app', 'Order'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(FaqCategories::className(), ['id' => 'category_id']);
    }

    public function getQuestion()
    {
        return $this->{'question_'. Yii::$app->language};
    }
    public function getAnswer()
    {
        return $this->{'answer_'. Yii::$app->language};
    }
}

models/News.php
<?php

namespace app\models;

use trntv\filekit\behaviors\UploadBehavior;
use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string $title_ru
 * @property string $title_uz
 * @property string $title_en
 * @property string $content_ru
 * @property string $content_uz
 * @property string $content_en
 * @property string $image_main
 * @property string $image_little
 * @property string $slug
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 */
class News extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'news';
    }
    public $base_file;
    public $base_file2;


    /**
     * @return array
     */
    public function behaviors ()
    {
        return [
            [
                'class' => UploadBehavior::className(),
                'attribute' => 'base_file',
                'pathAttribute' => 'image_main',
                'baseUrlAttribute' => false
            ],
            [
                'class' => UploadBehavior::className(),
                'attribute' => 'base_file2',
                'pathAttribute' => 'image_little',
                'baseUrlAttribute' => false
            ],
            [
                'class' => TimestampBehavior::className()
            ]
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title_ru', 'title_uz', 'title_en'], 'required'],
            [['content_ru', 'content_uz', 'content_en'], 'string'],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['title_ru', 'title_uz', 'title_en', 'image_main', 'image_little', 'slug'], 'string', 'max' => 255],
            [['base_file','base_file2'], 'safe']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title_ru' => Yii::t('app', 'Title Ru'),
            'base_file' => Yii::t('app', 'Main image'),
            'base_file2' => Yii::t('app', 'Little image'),
            'title_uz' => Yii::t('app', 'Title Uz'),
            'title_en' => Yii::t('app', 'Title En'),
            'content_ru' => Yii::t('app', 'Content Ru'),
            'content_uz' => Yii::t('app', 'Content Uz'),
            'content_en' => Yii::t('app', 'Content En'),
            'image_main' => Yii::t('app', 'Image Main'),
            'image_little' => Yii::t('app', 'Image Little'),
            'slug' => Yii::t('app', 'Slug'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }


    public function getTitle()
    {
        return $this->{'title_'.Yii::$app->language};
    }

    public function getContent()
    {
        return $this->{'content_'.Yii::$app->language};
    }
}

models/Offers.php
<?php

namespace app\models;

use trntv\filekit\behaviors\UploadBehavior;
use Yii;
use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "offers".
 *
 * @property int $id
 * @property string $image
 * @property string $airlines_ru
 * @property string $airlines_uz
 * @property string $airlines_en
 * @property string $flight_ru
 * @property string $flight_uz
 * @property string $flight_en
 * @property string $transfer_ru
 * @property string $transfer_uz
 * @property string $transfer_en
 * @property int $price
 * @property int $discount
 * @property string $slug
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 */
class Offers extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'offers';
    }

    public $base_file;

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className()

            ],
            [
                'class' => UploadBehavior::className(),
                'attribute' => 'base_file',
                'pathAttribute' => 'image',
                'baseUrlAttribute' => false
            ]
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['airlines_ru', 'airlines_uz', 'airlines_en'], 'required'],
            [['price', 'discount', 'status', 'created_at', 'updated_at'], 'integer'],
            [['image', 'airlines_ru', 'airlines_uz', 'airlines_en', 'flight_ru', 'flight_uz', 'flight_en', 'transfer_ru', 'transfer_uz', 'transfer_en', 'slug'], 'string', 'max' => 255],
            [['base_file'], 'safe']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'image' => Yii::t('app', 'Image'),
            'base_file' => Yii::t('app', 'Image'),
            'airlines_ru' => Yii::t('app', 'Airlines Ru'),
            'airlines_uz' => Yii::t('app', 'Airlines Uz'),
            'airlines_en' => Yii::t('app', 'Airlines En'),
            'flight_ru' => Yii::t('app', 'Flight Ru'),
            'flight_uz' => Yii::t('app', 'Flight Uz'),
            'flight_en' => Yii::t('app', 'Flight En'),
            'transfer_ru' => Yii::t('app', 'Transfer Ru'),
            'transfer_uz' => Yii::t('app', 'Transfer Uz'),
            'transfer_en' => Yii::t('app', 'Transfer En'),
            'price' => Yii::t('app', 'Price'),
            'discount' => Yii::t('app', 'Discount'),
            'slug' => Yii::t('app', 'Slug'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    public function getAirlines()
    {
        return $this->{'airlines_'.Yii::$app->language};
    }

    public function getFlight()
    {
        return $this->{'flight_'.Yii::$app->language};
    }
    public function getTransfer()
    {
        return $this->{'transfer_'.Yii::$app->language};
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\AboutUs;
use app\models\Advantages;
use app\models\Album;
use app\models\BaseModel;
use app\models\Callback;
use app\models\Contacts;
use app\models\FaqCategories;
use app\models\Faqs;
use app\models\Feedback;
use app\models\Follow;
use app\models\News;
use app\models\Offers;
use app\models\Pages;
use app\models\Partners;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class SiteController extends Controller
{

    /**
     * set Language from cookies
     *
     */
    public function init()
    {

        if (!empty(Yii::$app->request->cookies['language'])) {
            Yii::$app->language = Yii::$app->request->cookies['language'];
        } else {
            Yii::$app->language = 'ru';
        }
        parent::init();
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $base = new BaseModel();
        $about = AboutUs::findOne(1);
        $offers = Offers::find()->where(['status' => 1])->all();
        $subscribe = new Follow();
        if ($subscribe->load(Yii::$app->getRequest()->post()) && $subscribe->save()) {
            Yii::$app->session->setFlash('follow');
            return $this->refresh();
        }

        $news = News::find()->where(['status' => 1])->orderBy(['created_at' => SORT_DESC])->limit(3)->all();
        $partners = Partners::find()->where(['status' => 1, 'type' => 0])->all();
        $this->layout = 'index_layout';

        return $this->render('index', [
            'carousel' => $base->getCarousel(),
            'about' => $about,
            'offers' => $offers,
            'subscribe' => $subscribe,
            'news' => $news,
            'partners' => $partners

        ]);
    }


    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        $about = AboutUs::findOne(1);
        $partners = Partners::find()->where(['status' => 1, 'type' => 0])->all();

        return $this->render('about', [
            'about' => $about,
            'partners' => $partners,
        ]);
    }

    /**
     * @return string
     */
    public function actionNews()
    {
        $title = 'title_' . Yii::$app->language;
        $query = News::find()
            ->where(['status' => 1])
            ->andWhere(['not', [$title => '']]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 6]);
        $news = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->orderBy(['id' => SORT_DESC])
            ->all();

        return $this->render('news', [
            'news' => $news,
            'pages' => $pages
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionNewsPage($id)
    {
        $news = News::findOne($id);
        $lastNews = News::find()->where(['<>', 'id', $news->id])->orderBy(['id' => SORT_DESC])->limit(5)->all();
        return $this->render('news-page', [
            'news' => $news,
            'lastNews' => $lastNews
        ]);
    }

    /**
     * @return string
     */
    public function actionAlbum()
    {
        $query = Album::find()->where(['status' => 1])->orderBy(['id' => SORT_DESC]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 6]);
        $album = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('album', [
            'album' => $album,
            'pages' => $pages
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionAlbumImages($id)
    {
        $album = Album::findOne($id);

        return $this->render('album-page', [
            'album' => $album
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionOffers($id)
    {
        $offer = Offers::findOne($id);
        $partners = Partners::find()->where(['status' => 1, 'type' => 0])->all();

        return $this->render('offer', [
            'offer' => $offer,
            'partners' => $partners,
        ]);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContacts()
    {
        $contacts = Contacts::findOne(1);
        $feedback = new Feedback();
        if ($feedback->load(Yii::$app->request->post()) && $feedback->save()) {
            Yii::$app->session->setFlash('feedback');
            return $this->refresh();
        }
        return $this->render('contact', [
            'contacts' => $contacts,
            'feedback' => $feedback,
        ]);
    }

    public function actionFaq($id = null)
    {
        if (!$id) {
            $faq_id = FaqCategories::find()->limit(1)->one();
            $id = $faq_id->id;
        }
        $faqs = FaqCategories::find()->all();
        $faq = Faqs::find()->where(['category_id' => $id, 'status' => 1])->orderBy(['order' => SORT_ASC])->all();

        return $this->render('faq', [
            'faqs' => $faqs,
            'faq' => $faq,
            'id' => $id
        ]);


    }

    /**
     * @param $type
     * @return string
     */
    public function actionPage($type)
    {
        $page = Pages::findOne(['type' => $type]);
        $advantages = Advantages::find()->where(['status' => 1])->all();
        $partners = Partners::find()->where(['type' => '1', 'status' => 1])->all();

        return $this->render('page', [
            'page' => $page,
            'advantages' => $advantages,
            'partners' => $partners

        ]);
    }

    public function actionSetLanguage($l)
    {
        $langs = ['uz', 'ru', 'en'];
        if (in_array($l, $langs)) {
            Yii::$app->language = $l;
            Yii::$app->session->set('app_lang', $l);
            $cookies = Yii::$app->response->cookies;
            $cookies->add(new \yii\web\Cookie([
                'name' => 'language',
                'value' => $l,
            ]));
        }
        return $this->redirect(Yii::$app->request->referrer);

    }

    /**
     * Feedback AJAX
     * @return bool
     */
    public function actionFeedback()
    {
        $feed = new Feedback();
        if ($feed->load(Yii::$app->request->post()) && $feed->save()) {
            return true;
        }
        return false;
    }

    /**
     * Callback save AJAX
     * @return bool
     */
    public function actionCallback()
    {
        $feed = new Callback();
        if ($feed->load(Yii::$app->request->post()) && $feed->save()) {
            return true;
        }
        return false;
    }


}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error bg-white">
<div class="container regular-padding error-page-main">
    <div class="error-page-img">
        <img src="/images/404.jpg" alt="404-img" />
    </div>

    <a class="back-to-btn" href="/"><i class="fa fa-arrow-left"></i> Вернуться на главную</a>
</div>
</div>

views/site/faq.php
<?php
/**
 * Created by PhpStorm.
 * User: SoS
 * Date: 20.12.2018
 * Time: 15:38
 */

use yii\helpers\Url;

$this->title =  Yii::t('app','Часто задаваемые вопросы');
?>
<section class="head-top-wrap" style="background-image:url('/images/head-top-bg.png')">
    <div class="head-top-wrap-desc text-center wh-col">
        <h2><?= Yii::t('app','Помощь') ?></h2>
        <ul class="des-breadcrumb d-flex">
            <li><a href="/"><?= Yii::t('app', 'Главная') ?></a></li>
            <li><?= Yii::t('app','Помощь') ?></li>
        </ul>
    </div>
</section><!--end headTop-->
<div class="bg-white">
<main class="regular-padding container">
    <div class="heading">
        <h2 class="f-reg"><?= Yii::t('app','Часто задаваемые вопросы'); ?></h2>
    </div>

    <div class="row equal-offsets">
        <div class="col-md-4">
            <ul class="faq-cat-lst">
                <?php foreach ($faqs as $item):?>
                <li class="<?= $id == $item->id ? 'active' : '' ?>"><a href="<?= Url::to(['/site/faq','id' => $item->id]) ?>"><?= $item->name ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>

        <div class="col-md-8">
            <?php foreach ($faq as $item):?>
            <div class="faq-ques-box">
                <div class="faq-collapse-head">
                    <p class="faq-collapse-btn" data="sad">
                        <i><img src="/images/faq-icon.png" alt=""></i>
                        <span><?= $item->question ?></span>
                        <i class="fa fa-angle-right faq-arrow"></i>
                    </p>
                </div>
                <div class="faq-ques-txt txt-editor">
                    <span><?= $item->answer ?></span>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</main><!--end index FAQ-->
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = Yii::t('app', 'Главная страница');
?>

<!--********************start main slider********************-->

<div class="main-slider-wrap-con">
<section class="main-slider-wrap">
    <?php if (!empty($carousel)): ?>
        <?php foreach ($carousel as $item): ?>
            <div class="main-slider-elem" style="background-image: url('/uploads/<?= $item->image ?>')">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 main-slider-desc-wrap">
                            <p class="f-24"><?= $item->flight ? $item->flight : '' ?></p>
                             <p class="txt-arrow"><?= $item->transfer ? $item->transfer : '' ?> &nbsp;</p>
                            <p class="f-24 f-bold">
                                <?= Yii::t('app', 'от <span class="f-48">{price}</span> руб.', ['price' => $item->price]) ?>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</section><!--end main slider-->
</div>

<div class="ifarme-airline">
    <div id="root"></div>
<!--<iframe src="https://superkassa.ru/next/embedded/defaultExtra?partner=b9d1e78cdc8038ec50e2651e16c9329b" style="width: 100%; overflow: auto; margin: 0px; padding: 0px; border: medium none; background: transparent none repeat scroll 0% 0%; height: 196.367px;" onload="superkassaInit(this)" frameborder="0"></iframe>-->
</div>
<!--********************main about us********************-->

<div class="container-fluid">
    <div class="row">
        <?php if (!empty($about)): ?>
            <div class="col-md-6 no-padding main-about-img-wrap">
                <img src="/uploads/<?= $about->image1 ?>" alt="">
            </div>
            <div class="col-md-6 fx-c no-padding main-about-txt-desc-wrap">
                <div class="main-about-txt-desc wh-col">
                    <p><?= $about->about ? $about->about : '' ?></p>
                    <a href="<?= Url::to(['/site/about']) ?>"
                       class="bdr-radius full-pink-btn bl-xs-center"><?= Yii::t('app', 'Подробнее') ?></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div><!--end about us-->


<!--********************start special offers block********************-->

<div class="main-spec-wrap regular-padding bg-white">
    <div class="container">
        <div class="heading">
            <h2><?= Yii::t('app', 'Специальные предложения') ?></h2>
        </div>

        <div class="row spec-offers-slider-wrap">
            <?php if ($offers): ?>
                <?php foreach ($offers as $item): ?>
                    <a href="<?= Url::to(['/site/offers','id' => $item->id]) ?>" class="col-md-4">
                        <article class="spec-offers-elem wh-col"
                                 style="background-image: url('/uploads/<?= $item->image ?>')">
                            <?php if (!empty($item->discount)): ?>
                                <span class="spec-offers-elem-trgle">-<?= $item->discount ?>%</span>
                            <?php endif; ?>

                            <div class="spec-offers-elem-txt-desc">
                                <div>
                                    <h4><?= $item->airlines ?></h4>
                                    <p><?= $item->flight ?></p>
                                    <?php if(!empty($item->price)): ?>
                                    <p><?= Yii::t('app', ' от {price} руб.', ['price' => $item->price]) ?></p>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </article>
                    </a>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
</div><!--end special offers block-->


<!--********************start special offers block********************-->

<section class="main-contact-wrap regular-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 wh-col mb-lg-15 main-contact-sec-desc">
                <h3><?= Yii::t('app', 'Хочешь узнавать об акциях первым?') ?></h3>
                <p><?= Yii::t('app', 'Подпишись на рассылку!') ?></p>
            </div>
            <div class="col-lg-9">
                <?php $form = ActiveForm::begin() ?>
                <div class="main-contact-sec">
                    <div class="main-contact-sec-item f-40 mb-md-15">
                        <?= $form->field($subscribe, 'name')->textInput(['placeholder' => Yii::t('app', 'Имя')])->label(false) ?>
                    </div>
                    <div class="main-contact-sec-item f-60 w-but">
                        <?= $form->field($subscribe, 'email')->textInput(['type' => 'email', 'placeholder' => Yii::t('app', 'email')])->label(false) ?>
                        <button type="submit" class="bdr-radius subs-btn">Подписаться</button>
                    </div>
                </div>
                <?php ActiveForm::end() ?>
                <input type="hidden" value="<?= Yii::t('app', 'Спасибо за подписку!') ?>" id="followSwal">
                <?php if (Yii::$app->session->hasFlash('follow')): ?>
                    <?php $this->registerJs('
                                var swal_a = $("#followSwal").val();
                                swal(swal_a, "", "success");
                                '); ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section><!--end special offers block-->


<!--********************start main news********************-->
<div class="bg-white">
<div class="container regular-padding">
    <div class="heading text-center text-sm-left  d-flex justify-content-sm-between flex-column flex-sm-row">
        <h2><?= Yii::t('app', 'Новости компании') ?></h2>
        <a href="<?= Url::to(['/site/news']) ?>"
           class="bdr-radius all-news-btn pink-btn"><?= Yii::t('app', 'Все новости') ?></a>
    </div>

    <div class="row equal-offsets">
        <?php if (!empty($news)): ?>
            <?php foreach ($news as $item): ?>
                <div class="col-lg-4">
                    <article class="news-box">
                        <div class="news-box-img">
                            <img src="/uploads/<?= !empty($item->image_little) ? $item->image_little : $item->image_main ?>"
                                 alt="">
                        </div>

                        <div class="news-box-desc">
                            <div class="news-box-desc-date"><?= date('d.m.Y', $item->created_at) ?></div>
                            <a href="<?= Url::to(['/site/news-page','id' => $item->id]) ?>" class="link"><h4><?= $item->title ?></h4></a>
                            <p><?= $item->content ?></p>
                        </div>
                    </article>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
</div><!--end main news-->


<!--********************start payment system wrap********************-->
<div class="bg-white">
<div class="container ">
    <div class=" bordered regular-padding-2" style="border-top:1px solid #adadad">
        <div class="paym-sys-wrap">
            <?php if (!empty($partners)): ?>
                <?php foreach ($partners as $item): ?>
                    <a href="<?= $item->url ?>">
                        <img src="/uploads/<?= $item->image ?>" alt="<?= $item->name ?>">
                    </a>
                <?php endforeach ?>
            <?php endif; ?>
        </div>
    </div>
</div>
</div><!--end payment system wrap-->

views/site/news.php
<?php
/**
 * Created by PhpStorm.
 * User: SoS
 * Date: 19.12.2018
 * Time: 16:50
 */

use yii\helpers\Url;

$this->title = Yii::t('app', 'Новости')
?>

<!--********************start headTop********************-->

<section class="head-top-wrap" style="background-image:url('/images/head-top-bg.png')">
    <div class="head-top-wrap-desc text-center wh-col">
        <h2><?= Yii::t('app', 'Новости') ?></h2>
        <ul class="des-breadcrumb d-flex">
            <li><a href="/"><?= Yii::t('app', 'Главная') ?></a></li>
            <li><?= Yii::t('app', 'Новости') ?></li>
        </ul>
    </div>
</section><!--end headTop-->


<!--********************start news section********************-->
<div class="bg-white">
<main class="regular-padding container">
    <div class="row equal-offsets">
        <?php if (!empty($news)): ?>
            <?php foreach ($news as $item): ?>
                <div class="col-lg-4">
                    <article class="news-box">
                        <div class="news-box-img">
                            <img src="/uploads/<?= $item->image_little ?>" alt="<?= $item->title ?>">
                        </div>

                        <div class="news-box-desc">
                            <div class="news-box-desc-date"><?= date('d.m.Y', $item->created_at)?></div>
                            <a href="<?= Url::to(['/site/news-page','id' => $item->id]) ?>" class="link"><h4><?= $item->title ?></h4></a>
                            <p><?= mb_substr(strip_tags($item->content), 0,300) ?></p>
                        </div>
                    </article>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
    <?php
    echo \yii\widgets\LinkPager::widget([
        'pagination' => $pages,
        'options' => ['class' => 'des-pagination d-flex justify-content-center flex-wrap'],
        'prevPageLabel' => '&nbsp;',
        'nextPageLabel' => '&nbsp;',
        'prevPageCssClass' => 'des-pag-arrow left-arrow',
        'nextPageCssClass' => 'des-pag-arrow right-arrow',
        'activePageCssClass' => 'active',

    ]);?>
</main>
</div>

<!--end news section-->

views/site/offer.php
<?php
/**
 * Created by PhpStorm.
 * User: SoS
 * Date: 19.12.2018
 * Time: 18:02
 */
$this->title = $offer->airlines;
?>
<div class="main-slider-wrap-con">
<section class="main-slider-wrap">
     <?php if (!empty($offer)): ?>
            <div class="main-slider-elem" style="background-image: url('/uploads/<?= $offer->image ?>')">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 main-slider-desc-wrap">
                            <p class="f-24"><?= $offer->flight ? $offer->flight : '' ?></p>
                             <p class="txt-arrow"><?= $offer->transfer ? $offer->transfer : '' ?> &nbsp;</p>
                            <p class="f-24 f-bold">
                               <?= Yii::t('app', 'от <span class="f-48">{price}</span> руб.', ['price' => $offer->price]) ?>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
 <?php endif; ?>
</section><!--end main slider-->
</div>

<div class="ifarme-airline">
<iframe src="https://superkassa.ru/next/embedded/defaultExtra?partner=b9d1e78cdc8038ec50e2651e16c9329b" style="width: 100%; overflow: auto; margin: 0px; padding: 0px; border: medium none; background: transparent none repeat scroll 0% 0%; height: 196.367px;" onload="superkassaInit(this)" frameborder="0"></iframe>
</div>

<!--********************start payment system wrap********************-->
<div class="bg-white">
<div class="container ">
    <div class=" bordered regular-padding-2" >
        <div class="paym-sys-wrap">
            <?php if (!empty($partners)): ?>
                <?php foreach ($partners as $item): ?>
                    <a href="<?= $item->url ?>">
                        <img src="/uploads/<?= $item->image ?>" alt="<?= $item->name ?>">
                    </a>
                <?php endforeach ?>
            <?php endif; ?>
        </div>
    </div>
</div></div><!--end payment system wrap-->